# Generated by Django 4.1.6 on 2023-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=300)),
                ('age', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='complete',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
