# Generated by Django 4.1.6 on 2023-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_login_register_rename_complete_tasks_completed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
